"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
import {Icon} from "./icon";
import {useShop} from "./shop-provider";
export function Header(){
 const path=usePathname();const shop=useShop();const [open,setOpen]=useState(false);
 return <><a className="skip-link" href="#main">К содержимому</a><header className="site-header"><Link className="wordmark" href="/" aria-label="FLARE — главная">flare<span>↗</span></Link><nav className={open?"main-nav is-open":"main-nav"} aria-label="Основная навигация"><Link className={path.startsWith("/catalog")?"active":""} onClick={()=>setOpen(false)} href="/catalog">Скины <span>↗</span></Link><Link onClick={()=>setOpen(false)} href="/#steam">Пополнить Steam</Link><Link onClick={()=>setOpen(false)} href="/#gift-cards">Карты Apple</Link></nav><div className="header-actions"><Link className="cart-link" href="/cart" aria-label={`Корзина, товаров: ${shop.cart.length}`}><Icon name="cart"/><span>{shop.cart.length}</span></Link>{shop.loggedIn?<><Link className="button compact secondary" href="/account"><Icon name="user" size={17}/><span>Кабинет</span></Link><button className="icon-button logout-button" aria-label="Выйти" onClick={shop.logout}><Icon name="logout"/></button></>:<button className="button compact header-login" onClick={shop.login}><Icon name="steam" size={18}/><span>Войти через Steam</span></button>}<button className="icon-button mobile-toggle" aria-label={open?"Закрыть меню":"Открыть меню"} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name={open?"close":"menu"}/></button></div></header></>;
}
export function Footer(){return <footer className="flare-footer"><div className="footer-meta"><Link className="wordmark" href="/">flare<span>↗</span></Link><p>Для тех, кто играет по-своему.</p><nav aria-label="Внизу страницы"><Link href="/catalog">Скины</Link><Link href="/#steam">Steam</Link><Link href="/#gift-cards">Apple</Link><Link href="/account">Кабинет</Link></nav></div><Link className="footer-action" href="/catalog"><span>ТВОЙ ХОД</span><Icon name="diagonal" size={120}/></Link><div className="footer-baseline"><span>© FLARE, 2026</span><span>LESS DEFAULT. MORE YOU.</span><span>Карта / СБП</span></div></footer>;}
